"""empty message

Revision ID: c8881f06ccf8
Revises: 7d75cd99f304
Create Date: 2017-09-05 11:57:12.879332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8881f06ccf8'
down_revision = '7d75cd99f304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('match_resonses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_resonses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='match_resonses_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], name='match_resonses_response_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='match_resonses_pkey')
    )
    op.drop_table('match_responses')
    # ### end Alembic commands ###
